# Generated by Django 5.2.1 on 2025-06-01 19:48

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ciudad',
            field=models.CharField(blank=True, choices=[('villa_gesell', 'Villa Gesell'), ('pinamar', 'Pinamar'), ('madariaga', 'Madariaga')], default='villa_gesell', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(code='invalid_direccion', message='La dirección solo puede contener letras, números, espacios y caracteres especiales básicos.', regex='^[A-Za-z0-9\\s.,#-]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fecha_nacimiento',
            field=models.DateField(validators=[users.models.validate_birth_date]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='numero_afiliado',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_numero_afiliado', message='Número de afiliado debe contener entre 8 y 12 dígitos numéricos', regex='^\\d{8,12}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='obra_social',
            field=models.CharField(blank=True, choices=[('osde', 'OSDE'), ('swiss_medical', 'Swiss Medical'), ('galeno', 'Galeno'), ('medife', 'Medifé'), ('other', 'Other')], default='other', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('medic', 'Medic'), ('clinic', 'Clinic')], default='user', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='invalid_telefono', message='El teléfono debe contener entre 7 y 15 dígitos, opcionalmente con un prefijo internacional.', regex='^\\+?\\d{7,15}$')]),
        ),
    ]
